#!/usr/bin/env bash


export AGENT_TRACING_HOST=13.250.21.165:5775


#main.go
export OTTOPOINT_PURCHASE="0.0.0.0:8006"

export AGENT_TRACING_HOST_OTTOPOINT_PURCHASE=13.250.21.165:5775
export OTTOPOINT_PURCHASE_NAMESERVICE=ottopoint-purchase


export DB_POSTGRES_USER=OTTOAGcfg
export DB_POSTGRES_PASS="dTj*&56\$es"
export DB_POSTGRES_NAME="ottopoint"
export DB_POSTGRES_HOST="13.228.23.160"
export DB_POSTGRES_PORT="8432"
export DB_POSTGRES_DEBUG="true"
export DB_TYPE="postgres"
export DB_POSTGRES_SSL_MODE="disable"

# SIGNATURE
export OTTOPOINT_PURCHASE_HOST_SIGNATURE="http://13.228.25.85:8666"
export OTTOPOINT_PURCHASE_NAME_SIGNATURE="SIGNATURE"
export OTTOPOINT_PURCHASE_ENDPOINT_VALIDATE_SIGNATURE="/auth/signature"
export OTTOPOINT_PURCHASE_KEY_HEALTHCHECK_SIGNATURE="OTTOPOINT-PURCHASE:SIGNATURE"

# REDIS TOKEN
export OTTOPOINT_PURCHASE_HOST_REIDS_TOKEN="http://13.228.25.85:8703"
export OTTOPOINT_PURCHASE_NAME_REDIS_TOKEN="REDIS-TOKEN-OTTOPOINT"
export OTTOPOINT_PURCHASE_ENDPOINT_REDIS_TOKEN="/ottopoint/v0.1.0/redis/service"
export OTTOPOINT_PURCHASE_KEY_HEALTHCHECK_REDIS_TOKEN="OTTOPOINT-PURCHASE:REDIS_TOKEN_OTTOPOINT"

# OTTOAG
export OTTOPOINT_PURCHASE_OTTOAG_HOST="http://13.228.25.85:8089/"
export OTTOPOINT_PURCHASE_OTTOAG_ENDPOINT_INQUIRY="v1/inquiry"
export OTTOPOINT_PURCHASE_OTTOAG_ENDPOINT_PAYMENT="v1/payment"
export OTTOPOINT_PURCHASE_OTTOAG_SESSIONKEY="052CFD8A04F99AC48E4656BBDF19FE60"
export OTTOPOINT_PURCHASE_HEALTHCHECK_OTTOAG="OTTOPOINT-PURCHASE:OTTOAG"
export OTTOPOINT_PURCHASE_NAME_OTTOAG="OTTOAG"

#OPENLOYALTY
export OTTOPOINT_PURCHASE_HOST_OPL="http://54.179.186.194"
export OTTOPOINT_PURCHASE_NAME_OPL="OPENLOYALTY"
export OTTOPOINT_PURCHASE_HOST_VOUCHER_REDEEM="/api/customer/campaign/"
export OTTOPOINT_PURCHASE_HOST_VOUCHER_DETAIL="/api/campaign/"
export OTTOPOINT_PURCHASE_HOST_HISTORY_VOUCHER="/api/customer/campaign/bought"
export OTTOPOINT_PURCHASE_HOST_COUPONVOUCHER="/api/admin/campaign/coupons/mark_as_used"
export OTTOPOINT_PURCHASE_HOST_RULEPOINT="/api/customer/earnRule/"
export OTTOPOINT_PURCHASE_KEY_HEALTHCHECK_OPL="OTTOPOINT-PURCHASE:OPENLOYALTY"


cp /home/ubuntu/ottopoint-purchase .
nohup ./ottopoint-purchase > nohup.out 2>&1 &