export AGENT_TRACING_HOST=13.250.21.165:5775


#main.go
export OTTOPOINT_PURCHASE="8006"

export AGENT_TRACING_HOST_OTTOPOINT_PURCHASE=13.250.21.165:5775
export OTTOPOINT_PURCHASE_NAMESERVICE=ottopoint-purchase

# DB
export POSTGRES_USER="opointuser"
export POSTGRES_PASS="9RJ49W3FUqGznayh"
export POSTGRES_NAME="ottopoint"
export POSTGRES_HOST="34.101.175.164"
export POSTGRES_PORT="8432"
export POSTGRES_DEBUG="true"
export TYPE="postgres"
export POSTGRES_SSL_MODE="disable"

# SIGNATURE
export OTTOPOINT_PURCHASE_HOST_SIGNATURE="http://34.101.175.164:8666"
export OTTOPOINT_PURCHASE_NAME_SIGNATURE="SIGNATURE"
export OTTOPOINT_PURCHASE_ENDPOINT_VALIDATE_SIGNATURE="/auth/signature"                                                                   
export OTTOPOINT_PURCHASE_KEY_HEALTHCHECK_SIGNATURE="OTTOPOINT-PURCHASE:SIGNATURE"    

# REDIS TOKEN                                                                                                                             
export OTTOPOINT_PURCHASE_HOST_REIDS_TOKEN="http://34.101.175.164:8703"
export OTTOPOINT_PURCHASE_NAME_REDIS_TOKEN="REDIS-TOKEN-OTTOPOINT"
export OTTOPOINT_PURCHASE_ENDPOINT_REDIS_TOKEN="/ottopoint/v0.1.0/redis/service"
export OTTOPOINT_PURCHASE_KEY_HEALTHCHECK_REDIS_TOKEN="OTTOPOINT-PURCHASE:REDIS_TOKEN_OTTOPOINT"
export HOST_ADDRESS_OTTOPOINT_AUTH="http://34.101.175.164:8666"
export HOSTADDRES_REDIS_SERVICE="http://34.101.175.164:8703"
export HOST_PUBLISHER="http://34.101.175.164:8703"

export OTTOPOINT_PURCHASE_ENDPOINT_REDIS_TOKEN="/ottopoint/v0.1.0/redis/service"
export OTTOPOINT_PURCHASE_KEY_HEALTHCHECK_REDIS_TOKEN="OTTOPOINT-PURCHASE:REDIS_TOKEN_OTTOPOINT"
export HOST_ADDRESS_OTTOPOINT_AUTH="http://34.101.175.164:8666"
export HOSTADDRES_REDIS_SERVICE="http://34.101.175.164:8703"
export HOST_PUBLISHER="http://34.101.175.164:8703"

# OTTOAG
export OTTOPOINT_PURCHASE_OTTOAG_HOST="http://13.228.25.85:8089/"
export OTTOPOINT_PURCHASE_OTTOAG_ENDPOINT_INQUIRY="v1/inquiry"
export OTTOPOINT_PURCHASE_OTTOAG_ENDPOINT_PAYMENT="v1/payment"
export OTTOPOINT_PURCHASE_OTTOAG_SESSIONKEY="052CFD8A04F99AC48E4656BBDF19FE60"
export OTTOPOINT_PURCHASE_HEALTHCHECK_OTTOAG="OTTOPOINT-PURCHASE:OTTOAG"
export OTTOPOINT_PURCHASE_NAME_OTTOAG="OTTOAG"
export OTTOPOINT_PURCHASE_OTTOAG_SESSIONKEY="052CFD8A04F99AC48E4656BBDF19FE60"
export OTTOPOINT_PURCHASE_OTTOAG_AUTHORIZATION="T1RQT0lOVA=="
export OTTOPOINT_PURCHASE_OTTOAG_MEMBERID="OTPOINT"


#OPENLOYALTY
#export OTTOPOINT_PURCHASE_HOST_OPL="http://18.138.173.105"
export OTTOPOINT_PURCHASE_HOST_OPL="https://openloyalty-stg.ottopoint.id"
export OTTOPOINT_PURCHASE_NAME_OPL="OPENLOYALTY"
export OTTOPOINT_PURCHASE_HOST_VOUCHER_REDEEM="/api/customer/campaign/"
export OTTOPOINT_PURCHASE_HOST_VOUCHER_DETAIL="/api/campaign/"
export OTTOPOINT_PURCHASE_HOST_HISTORY_VOUCHER="/api/customer/campaign/bought"
export OTTOPOINT_PURCHASE_HOST_COUPONVOUCHER="/api/admin/campaign/coupons/mark_as_used"
export OTTOPOINT_PURCHASE_HOST_RULEPOINT="/api/customer/earnRule/"
export OTTOPOINT_PURCHASE_KEY_HEALTHCHECK_OPL="OTTOPOINT-PURCHASE:OPENLOYALTY"

#UV
# export OTTOPOINT_PURCHASE_HOST_UV="http://13.228.25.85/uv-service/v0.1.0"
export OTTOPOINT_PURCHASE_HOST_UV="http://34.101.175.164:8704/uv-service/v0.1.0"
export HTTP_TIMEOUT_UV="60s"

#VOUCHER AGGREGATOR
export OTTOPOINT_PURCHASE_HOST_VOUCHERAG="http://localhost:8480/transaction"
export OTTOPOINT_PURCHASE_NAME_VOUCHERAG="VOUCHER AGGREGATOR"
export OTTOPOINT_PURCHASE_HOST_VOUCHERAR_ORDER="/v1/order"
export OTTOPOINT_PURCHASE_HOST_VOUCHERAR_CHECK_STATUS="/v1/order/status"
export OTTOPOINT_PURCHASE_HOST_CALLBACK_VOUCHERAG="http://34.101.175.164:8006"
export OTTOPOINT_PURCHASE_CALLBACK_VOUCHERAG="/transaction/v2/redeem/voucherag"


# OTTOPOINT-COREPOINT
export HOST_COREPOINT="http://34.101.175.164:8481"
export HOST_OTTOPOINT_COREPOINT="http://34.101.175.164:8402"

go run main.go

# Build

git pull origin dev

./kill.sh

export GO111MODULE="on"

go build -o ottopoint-purchase

export GO111MODULE="off"

nohup ./ottopoint-purchase > nohup.out 2>&1 &