package models

type BuyVocuherResp struct {
	Coupons []GetCoupons `json:"coupons"`
	Error   string       `json:"error"` // jika error
	Code    int          `json:"code"`  // jika error
	Message string       `json:"message"`
}

type GetCoupons struct {
	Id   string `json:"id"`
	Code string `json:"code"`
}

type AutoGenerated struct {
	Coupons []struct {
		Code string `json:"code"`
		ID   string `json:"id"`
	} `json:"coupons"`
}
